name: 'Install'
description: 'Sets up Node.js and runs install'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        run_install: false

    - run: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'pnpm'
        node-version-file: .node-version

    - name: Preinstallation steps
      shell: bash
      run: corepack enable

    - uses: nrwl/nx-set-shas@v4

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
