# Adapted from create-t3-app.
name: Publish

on:
  pull_request:
    types: [labeled]
    branches:
      - main
  push:
    paths:
      - '.changeset/**'
      - 'packages/**'
    branches:
      - main

jobs:
  prerelease:
    if: |
      github.event_name == 'pull_request' &&
      github.repository_owner == 'SaulMoro' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      contains(github.event.pull_request.labels.*.name, '🚀 autorelease')
    name: Build & Publish a beta release to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/composite-actions/install

      - name: Configure npm registry for trusted publishing
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          registry-url: 'https://registry.npmjs.org'

      - name: Modify package.json version
        run: node .github/version-script-beta.mjs

      - name: Publish Beta to NPM
        run: pnpm pub:beta

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: packages/ngrx-rtk-query

      - name: Upload packaged artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-package-ngrx-rtk-query@${{ steps.package-version.outputs.current-version }}-pr-${{ github.event.number }}
          path: dist/packages/ngrx-rtk-query/

  release:
    if: ${{ github.event_name == 'push' && github.repository_owner == 'SaulMoro' }}
    name: Create a PR for release workflow
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/composite-actions/install

      - name: Configure npm registry for trusted publishing
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          registry-url: 'https://registry.npmjs.org'

      - name: Check for errors
        run: pnpm affected:lint

      - name: Build ngrx-rtk-query package
        run: pnpm build:ngrx-rtk-query

      - name: Create Version PR or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore(release): version packages'
          title: 'chore(release): version packages'
          version: node .github/changeset-version.mjs
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: 'production'
